sgt/app/urls.py
from django.urls import path
from . import views


# app_name = "app" 

urlpatterns = [
	path('', views.index, name='index'),
	path('senha/', views.change_password, name='change_password'),
	path('password_reset/', views.password_reset_request, name='password_reset'),
	path('cursos/', views.cursos_list, name='cursos_list'),
	path('disciplinas/', views.disciplinas_list, name='disciplinas_list'),
	path('disciplina/new/', views.disciplina_new, name='disciplina_new'),
	path('disciplina/<int:pk>/edit/', views.disciplina_edit, name='disciplina_edit'),
	path('docentes/', views.docentes_list, name='docentes_list'),
	path('docente/new/', views.docente_new, name='docente_new'),
	path('docente/<int:pk>/edit/', views.docente_edit, name='docente_edit'),
	path('discentes/', views.discentes_list, name='discentes_list'),
	path('discente/new/', views.discente_new, name='discente_new'),
	path('discente/<int:pk>/edit/', views.discente_edit, name='discente_edit'),
	path('discente/<int:pk>/off/', views.discente_off, name='discente_off'),
	path('discente/<int:pk>/on/', views.discente_on, name='discente_on'),
	path('tutorias/', views.tutorias_list, name='tutorias_list'),
	path('tutoria/new/', views.tutoria_new, name='tutoria_new'),
	path('tutoria/<int:pk>/edit/', views.tutoria_edit, name='tutoria_edit'),
	path('tutoria/<int:pk>/remove/', views.tutoria_remove, name='tutoria_remove'),
	path('tutoria/<int:pk>/export/', views.tutoria_export, name='tutoria_export'),
	# path('tutoria/<int:pk>/disciplinas_cursadas/', views.tutoria_disciplinas_cursadas, name='tutoria_disciplinas_cursadas'),
	path('tutoria/<int:pk>/estagios/', views.tutoria_estagios_list, name='tutoria_estagios_list'),
	path('tutoria/<int:pk>/estagios/new', views.tutoria_estagio_new, name='tutoria_estagio_new'),
	path('tutoria/<int:pk>/estagios/<int:pk_1>/edit', views.tutoria_estagio_edit, name='tutoria_estagio_edit'),	
	path('tutoria/<int:pk>/estagios/<int:pk_1>/remove', views.tutoria_estagio_remove, name='tutoria_estagio_remove'),	
	path('tutoria/<int:pk>/atividades_complementares/', views.tutoria_atividades_complementares_list, name='tutoria_atividades_complementares_list'),
	path('tutoria/<int:pk>/atividades_complementares/new', views.tutoria_atividade_complementar_new, name='tutoria_atividade_complementar_new'),	
	path('tutoria/<int:pk>/atividades_complementares/<int:pk_1>/edit', views.tutoria_atividade_complementar_edit, name='tutoria_atividade_complementar_edit'),	
	path('tutoria/<int:pk>/atividades_complementares/<int:pk_1>/remove', views.tutoria_atividade_complementar_remove, name='tutoria_atividade_complementar_remove'),	
	path('tutoria/<int:pk>/atividades_extracurriculares/', views.tutoria_atividades_extracurriculares_list, name='tutoria_atividades_extracurriculares_list'),
	path('tutoria/<int:pk>/atividades_extracurriculares/new', views.tutoria_atividade_extracurricular_new, name='tutoria_atividade_extracurricular_new'),
	path('tutoria/<int:pk>/atividades_extracurriculares/<int:pk_1>/edit', views.tutoria_atividade_extracurricular_edit, name='tutoria_atividade_extracurricular_edit'),	
	path('tutoria/<int:pk>/atividades_extracurriculares/<int:pk_1>/remove', views.tutoria_atividade_extracurricular_remove, name='tutoria_atividade_extracurricular_remove'),	
	path('orientacoes_matricula/', views.orientacoes_matricula_list, name='orientacoes_matricula_list'),
	path('orientacoes_matricula/new/', views.orientacao_matricula_new, name='orientacao_matricula_new'),
	path('orientacoes_matricula/<int:pk>/edit/', views.orientacao_matricula_edit, name='orientacao_matricula_edit'),
	path('orientacoes_matricula/<int:pk>/remove/', views.orientacao_matricula_remove, name='orientacao_matricula_remove'),
	path('orientacoes_matricula/<int:pk>/export/', views.orientacao_matricula_export, name='orientacao_matricula_export'),	
]

sgt/sgt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('accounts/login/', views.LoginView.as_view(), name='login'),
    path('accounts/logout/', views.LogoutView.as_view(next_page='/'), name='logout'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='app/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="app/password_reset_confirm.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='app/password_reset_complete.html'), name='password_reset_complete'), 
]

sgt/app/forms.py
from django import forms
from .models import Curso, Disciplina, TutoriaDisciplina, Docente, Discente, Orientacaomatricula, Tutoria, Atividadecomplementar, Estagioextracurricular, Atividadeextracurricular
from django.core.validators import MaxValueValidator, MinValueValidator 

class DateInput(forms.DateInput):
	input_type = 'date'

class TutoriaDisciplinaForm(forms.ModelForm):
	# tutoria = forms.CharField(required=False, widget=forms.HiddenInput)
	disciplinas = forms.ModelMultipleChoiceField(label='Disciplinas já cursadas', required=False, widget=forms.CheckboxSelectMultiple, queryset=None)
	curso = forms.CharField(label='Curso', required=False)

	class Meta:
		model = TutoriaDisciplina
		fields = ('curso', 'disciplinas')

	def __init__(self, *args, **kwargs):
		self.tut = kwargs.pop('tut')
		super(TutoriaDisciplinaForm, self).__init__(*args, **kwargs)
		# self.fields['docente'].initial = self.doc[0].nome
		# if self.ppp == 'add' or self.ppp == 'upd_n':
		if self.tut != '':
			self.fields['curso'].initial = self.tut.discente.curso
			# self.fields['tutoria'].initial = self.tut
			# self.fields['tutoria'].widget.attrs.update({'selected-option': self.tut.id})
			self.fields['disciplinas'].queryset = Disciplina.objects.filter(curso=self.tut.discente.curso).order_by('nome')

class DisciplinaForm(forms.ModelForm):
	# curso = forms.ModelChoiceField(queryset=Curso.objects.all())
	YES_OR_NO=[(None,'--------'), (True, 'Sim'), (False, 'Não')]
	DIAS_SEMANA=[(2, 'Segunda'), (3, 'Terça'), (4, 'Quarta'), (5, 'Quinta'), (6, 'Sexta'), (7, 'Sábado')]

	carga_horaria = forms.IntegerField(label='Carga Horária')
	carga_horaria.widget.attrs.update({'class': 'hideArrows'})
	ativa = forms.ChoiceField(label='Disciplina Ativa', choices=YES_OR_NO, widget=forms.Select)
	
	horario_semana = forms.MultipleChoiceField(label='Dias da aula', required=False, choices=DIAS_SEMANA, widget=forms.CheckboxSelectMultiple)
	hora_aula_inicio = forms.CharField(label='Início da aula', required=False)
	hora_aula_inicio.widget.attrs.update({'placeholder':'00:00', 'data-mask': '00:00'})
	hora_aula_fim = forms.CharField(label='Fim da aula', required=False)
	hora_aula_fim.widget.attrs.update({'placeholder':'00:00', 'data-mask': '00:00'})

	class Meta:
		model = Disciplina
		fields = ('nome', 'carga_horaria', 'horario_semana', 'hora_aula_inicio', 'hora_aula_fim' , 'curso', 'ativa')


	def __init__(self, *args, **kwargs):
		self.op = kwargs.pop('op')
		self.disc = kwargs.pop('disc')
		super(DisciplinaForm, self).__init__(*args, **kwargs)
		print(self.disc.horario_semana)
		print(self.fields['horario_semana'].choices)
		# print(self.disc.horario_semana)

		lista_horarios_disciplina = []
		for i in self.disc.horario_semana:
			if (i.isnumeric()):
				lista_horarios_disciplina.append(int(i))
		
		print(lista_horarios_disciplina)

		if self.op == 'upd':
			self.fields['horario_semana'].initial = lista_horarios_disciplina

		# self.fields['docente'].required = False
		# self.fields['docente'].widget.attrs.update({'selected-option': self.doc[0].id})
		# self.fields['discente'].queryset = Discente.objects.filter(curso=self.doc[0].curso).order_by('nome')
		# self.fields['horario_semana'].queryset = Disciplina.objects.filter()


class EstagioExtraCurricularForm(forms.ModelForm):
	
	YES_OR_NO=[(None,'--------'), (True, 'Sim'), (False, 'Não')]

	descricao = forms.CharField(max_length=200, label='Descrição')
	carga_horaria = forms.IntegerField(label='Carga Horária')
	carga_horaria.widget.attrs.update({'class': 'hideArrows'})
	data_inicio = forms.DateField(label='Início')
	data_inicio.widget.attrs.update({'data-mask': '00/00/0000'})
	data_fim = forms.DateField(label='Término', required=False)
	data_fim.widget.attrs.update({'data-mask': '00/00/0000'})
	remunerado = forms.ChoiceField(label='Remunerado?', choices=YES_OR_NO, widget=forms.Select)

	class Meta:
		model = Estagioextracurricular
		fields = ('descricao', 'remunerado', 'carga_horaria', 'data_inicio', 'data_fim')

class AtividadeComplementarForm(forms.ModelForm):

	descricao = forms.CharField(max_length=200, label='Descrição')
	carga_horaria = forms.IntegerField(label='Carga Horária')
	carga_horaria.widget.attrs.update({'class': 'hideArrows'})

	class Meta:
		model = Atividadecomplementar
		fields = ('descricao', 'carga_horaria')


class AtividadeExtraCurricularForm(forms.ModelForm):

	TIPO_ATIVIDADE_EC=[(None,'--------'),('ENS','Ensino'), ('PES','Pesquisa'), ('EXT', 'Extensão')]
	YES_OR_NO=[(None,'--------'), (True, 'Sim'), (False, 'Não')]

	descricao = forms.CharField(max_length=200, label='Descrição')
	tipo = forms.ChoiceField(label='Tipo de Atividade', choices=TIPO_ATIVIDADE_EC, widget=forms.Select)
	bolsista = forms.ChoiceField(label='Bolsista?', choices=YES_OR_NO, widget=forms.Select)

	class Meta:
		model = Atividadeextracurricular
		fields = ('descricao', 'tipo', 'bolsista')

class TutoriaForm(forms.ModelForm):

	NO_OR_YES=[('N', 'Não'),('S', 'Sim')]

	# docente = forms.CharField(max_length=200)
	# docente.widget.attrs.update({'disabled': 'disabled'})
	legislacoes_ifbaiano = forms.CharField(label='Você conhece legislações e documentos referentes ao seu curso e ao IF Baiano? Quais?', required=False, widget=forms.Textarea(attrs={'rows': 5}))
	dificuldades_semestre_atual = forms.CharField(label='Quais disciplinas do semestre atual que você está tendo maior dificuldade? Porque?',
     required=False, widget=forms.Textarea(attrs={'rows': 5}))
	acoes = forms.CharField(label='Quais ações você acha que poderiam ajudar nessas disciplinas?', 
     required=False, widget=forms.Textarea(attrs={'rows': 5}))
	sugestoes_dif_semestre = forms.CharField(label='Sugestão(ões) do(a) Tutor(a) para melhorar o rendimento nas disciplinas com dificuldade:',
     required=False, widget=forms.Textarea(attrs={'rows': 5}))
	dificuldades_curso = forms.CharField(label='Qual(is) outra(as) dificuldades você tem enfrentado durante o curso?',
     required=False, widget=forms.Textarea(attrs={'rows': 5}))
	sugestoes_dif_curso = forms.CharField(label='Sugestão(ões) do(a) Tutor(a) para o enfrentamento dessas dificuldades:', 
     required=False, widget=forms.Textarea(attrs={'rows': 5}))
	observacoes = forms.CharField(label='Outras observações do(a) Tutor(a):',
     required=False, widget=forms.Textarea(attrs={'rows': 5}))
	status = forms.ChoiceField(label='Deseja finalizar a tutoria?',
     choices=NO_OR_YES, widget=forms.Select, required=False)
	# docente = forms.ChoiceField(required=False, widget=forms.Select)
	disciplinas_cursadas = forms.ModelMultipleChoiceField(label='Disciplinas já cursadas', required=False, widget=forms.CheckboxSelectMultiple, queryset=None)

	class Meta:
		model = Tutoria
		fields = ('docente', 'discente', 'legislacoes_ifbaiano', 'dificuldades_semestre_atual', 'acoes',
			'sugestoes_dif_semestre', 'dificuldades_curso', 'sugestoes_dif_curso', 'observacoes', 'status', 'disciplinas_cursadas')

	def __init__(self, *args, **kwargs):
		self.doc = kwargs.pop('doc')
		super(TutoriaForm, self).__init__(*args, **kwargs)
		# self.fields['docente'].initial = self.doc[0].nome
		# if self.ppp == 'add' or self.ppp == 'upd_n':
		self.fields['docente'].required = False
		self.fields['docente'].widget.attrs.update({'selected-option': self.doc[0].id})
		self.fields['discente'].queryset = Discente.objects.filter(curso=self.doc[0].curso).order_by('nome')
		self.fields['disciplinas_cursadas'].queryset = Disciplina.objects.filter(curso=self.doc[0].curso).order_by('nome')

class DocenteForm(forms.ModelForm):
	# curso = forms.ModelChoiceField(queryset=Curso.objects.all())
	senha = forms.CharField(max_length=32, widget=forms.PasswordInput)
	email = forms.CharField(max_length=100, label='E-mail')
	siape = forms.IntegerField(label='SIAPE')
	siape.widget.attrs.update({'class': 'hideArrows'}) 
	# confirmar_senha = forms.CharField(max_length=32, widget=forms.PasswordInput)

	# def clean(self):
	#     cleaned_data = super(DocenteForm, self).clean()

	#     password = cleaned_data.get('senha')
	#     password_confirm = cleaned_data.get('confirmar_senha ')

	#     if password and password_confirm:
	#         if password != password_confirm:
	#             raise forms.ValidationError("As senhas não correspondem")
	#     return cleaned_data

	class Meta:
		model = Docente
		fields = ('nome', 'curso', 'email', 'siape',)

	def __init__(self, *args, **kwargs):
		self.op = kwargs.pop('op')
		super(DocenteForm, self).__init__(*args, **kwargs)
		# self.fields['docente'].initial = self.doc[0].nome
		if self.op == 'upd':
			self.fields['senha'].required = False
			self.fields['senha'].widget.attrs.update({'hidePwdField':'S'})

class OrientacaoMatriculaForm(forms.ModelForm):

	NO_OR_YES=[('N', 'Não'),('S', 'Sim')]

	disciplinas = forms.ModelMultipleChoiceField(label='Disciplinas a serem cursadas no próximo semestre', required=False, widget=forms.CheckboxSelectMultiple, queryset=None)
	status = forms.ChoiceField(label='Deseja finalizar a tutoria?',
     choices=NO_OR_YES, widget=forms.Select, required=False)

	class Meta:
		model = Orientacaomatricula
		fields = ('docente', 'discente', 'disciplinas', 'status')

	def __init__(self, *args, **kwargs):
		self.doc = kwargs.pop('doc')
		super(OrientacaoMatriculaForm, self).__init__(*args, **kwargs)
		# self.fields['docente'].initial = self.doc[0].nome
		# if self.ppp == 'add' or self.ppp == 'upd_n':
		self.fields['docente'].required = False
		self.fields['docente'].widget.attrs.update({'selected-option': self.doc[0].id})
		self.fields['discente'].queryset = Discente.objects.filter(curso=self.doc[0].curso).order_by('nome')
		self.fields['disciplinas'].queryset = Disciplina.objects.filter(curso=self.doc[0].curso).order_by('nome')


class DiscenteForm(forms.ModelForm):

	######################################### CONSTANTES #########################################
	GENERO=[(None,'--------'),('M','Masculino'), ('F','Feminino')]
	YES_OR_NO=[(None,'--------'), (True, 'Sim'), (False, 'Não')]
	NO_OR_YES=[('N', 'Não'),('S', 'Sim')]

sgt/app/templates/app/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description"
            content="Sistema de Gestão de Tutorias">
        <title>Sistema de Gestão de Tutorias</title>

        <!-- using online links -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
            integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css"
            integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
        <link rel="stylesheet" href="//malihu.github.io/custom-scrollbar/jquery.mCustomScrollbar.min.css">

        <!-- using local links -->
        <!-- <link rel="stylesheet" href="../node_modules/bootstrap/dist/css/bootstrap.min.css">
        <link rel="stylesheet" href="../node_modules/@fortawesome/fontawesome-free/css/all.min.css">
        <link rel="stylesheet" href="../node_modules/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.css"> -->

        <link rel="stylesheet" href="{% static 'css/login.css' %}">
<!--         <link rel="stylesheet" href="{% static 'css/sidebar-themes.css' %}">
        <link rel="shortcut icon" type="image/png" href="{% static 'img/favicon.png' %}" /> -->
    </head>

    <body>

        <div class="wrapper fadeInDown">
          <div id="formContent">
            <!-- Tabs Titles -->

            <!-- Icon -->
<!--             <div class="fadeIn first">
              <img src="http://danielzawadzki.com/codepen/01/icon.svg" id="icon" alt="User Icon" />
            </div> -->

            {% block content %}
            {% endblock %}

            <!-- Remind Passowrd -->
            <div id="formFooter">
              <a class="underlineHover" href="{% url 'password_reset' %}">Esqueceu sua senha?</a>
            </div>

          </div>
        </div>
    </body>
</html>

sgt/app/templates/app/cursos_list.html
{% extends 'app/base2.html' %}

{% block content %}
    <div class="row">
        <div class="form-group col-md-12">
            <h2>Cursos</h2>
        </div>
    </div>
    <hr>
    <div class="row table-responsive">
        <table class="table table-borderless table-hover">
            <thead class="thead-light">
              <th scope="col">Nome</th>
              <th scope="col">Turno</th>
            </thead>
            <tbody>
              {% for curso in cursos %}
              <tr>
                <td>{{ curso.nome }}</td><td>{{ curso.turno }}</td>
              </tr>
              {% endfor %}        
            </tbody>
        </table>
    </div>  
{% endblock %}

sgt/app/templates/app/discentes_list.html
{% extends 'app/base2.html' %}

{% block content %}
    <div class="row">
        <div class="form-group col-md-12">
            <h2>Discentes</h2>
        </div>
    </div>
    <hr>
    <div class="row table-responsive">
        <table class="table table-borderless table-hover">
            <thead class="thead-light">
              <th scope="col">Nome</th>
              <th scope="col">Matrícula</th>
              <th scope="col">Curso</th>
              <th scope="col">Ano Ingresso</th>
              <th scope="col"></th>
              {% ifequal user.groups.all.0.name "Coordenador" %}
                <th scope="col"></th>
              {% endifequal %}
            </thead>
            <tbody>
              {% for disc in discentes %}

               {% if disc.ativo %}
                <tr>
               {% else %}
                <tr style="color:red;">
               {% endif %}

                <td>{{ disc.nome }}</td>
                <td>{{ disc.matricula }}</td>
                <td>{{ disc.curso.nome }}</td>
                
                <td>
                    {{ disc.ano_ingresso }} 
                </td>
                <!-- buttons -->
                <td><a href="{% url 'discente_edit' pk=disc.pk %}">Editar</a></td>
                {% ifequal user.groups.all.0.name "Coordenador" %}
                    {% if disc.ativo %}
                      <td><a href="{% url 'discente_off' pk=disc.pk %}">Desativar</a></td>
                    {% else %}
                      <td><a href="{% url 'discente_on' pk=disc.pk %}">Reativar</a></td>
                    {% endif %}
                {% endifequal %}
              </tr>
              {% endfor %}        
            </tbody>
        </table>
    </div> 

    <div class="row add-table">
      <a href="{% url 'discente_new' %}" class="top-menu"><span class="glyphicon glyphicon-plus">Adicionar Discente</span></a>
    </div> 
{% endblock %}

sgt/app/templates/app/disciplina_new.html
{% extends 'app/base2.html' %}

{% load crispy_forms_tags %}

{% block content %}
	<form method="POST">
    	{% csrf_token %}
        {% ifequal op "upd" %}
            <h2>Editar Disciplina</h2>
        {% else %}
            <h2>Nova Disciplina</h2>
        {% endifequal %}
        <br>
    	<hr>
		<h4>Geral</h4>
            <div class="row">
                <div class="col-8">
                  {{ form.nome|as_crispy_field }}
                </div>
            </div>
			<div class="row">
                <div class="col-8">
                  {{ form.curso|as_crispy_field }}
                </div>
            </div>
            <div class="row">
                <div class="col-4">
                    {{ form.carga_horaria|as_crispy_field }}
                </div>
                <div class="col-4">
                    {{ form.ativa|as_crispy_field }}
                </div>
            </div>
        <hr>
		<h4>Horário no Semestre atual</h4>
            <div class="row">
                <div class="col-4">
                    {{ form.horario_semana|as_crispy_field }}
                </div>
            </div>
            <div class="row">
                <div class="col-4">
                    {{ form.hora_aula_inicio|as_crispy_field }}
                </div>
                <div class="col-4">
                    {{ form.hora_aula_fim|as_crispy_field }}
                </div>
            </div>
        
        <button type="submit" class="btn btn-success">Salvar</button>
    </form>
{% endblock %}

sgt/app/templates/app/disciplinas_list.html
{% extends 'app/base2.html' %}

{% block content %}
    <div class="row">
        <div class="form-group col-md-12">
            <h2>Disciplinas</h2>
        </div>
    </div>
    <hr>
    <div class="row table-responsive">
        <table class="table table-borderless table-hover">
            <thead class="thead-light">
              <th scope="col">Nome</th>
              <th scope="col">Carga Horária</th>
              <th scope="col">Curso</th>
              <th scope="col"></th>
            </thead>
            <tbody>
              {% for disc in disciplinas %}

              {% if disc.ativa %}
                <tr>
              {% else %}
                <tr style="color:red;">
              {% endif %}
                <td>{{ disc.nome }}</td>
                <td style="text-align: center">{{ disc.carga_horaria }} horas</td>
                
                <td>
                    {{ disc.curso.nome }} 
                </td>
                <!-- buttons -->
                <td><a href="{% url 'disciplina_edit' pk=disc.pk %}">Editar</a></td>
              </tr>
              {% endfor %}        
            </tbody>
        </table>
    </div> 

    <div class="row add-table">
      <a href="{% url 'disciplina_new' %}" class="top-menu"><span class="glyphicon glyphicon-plus">Adicionar Disciplina</span></a>
    </div> 
{% endblock %}

sgt/app/templates/app/docente_new.html
{% extends 'app/base2.html' %}

{% load crispy_forms_tags %}

{% block content %}
    <form method="POST">
    	{% csrf_token %}
        {% ifequal op "upd" %}
            <h2>Editar Docente</h2>
        {% else %}
            <h2>Novo Docente</h2>
        {% endifequal %}
    	<hr>
		<div class="row">
            <div class="col-8">
              {{ form.nome|as_crispy_field }}
            </div>
        </div>
		<div class="row">
            <div class="col-8">
              {{ form.curso|as_crispy_field }}
            </div>
        </div>
        <div class="row">
            <div class="col-4">
                {{ form.email|as_crispy_field }}
            </div>
            <div class="col-4">
                {{ form.siape|as_crispy_field }}
            </div>
        </div>
        <div class="row">
            <div class="col-4">
                {{ form.senha|as_crispy_field }}
            </div>
        </div>

        
        <button type="submit" class="btn btn-success">Salvar</button>
    </form>
{% endblock %}

{% block js %}
    <script type="text/javascript">
    	if($("#id_senha").attr("hidePwdField") == 'S'){
            $("#div_id_senha").hide();
        } else {
        	$("#div_id_senha").show();
        }
    </script>
{% endblock %}

sgt/app/templates/app/docentes_list.html
{% extends 'app/base2.html' %}

{% block content %}
    <div class="row">
        <div class="form-group col-md-12">
            <h2>Docentes</h2>
        </div>
    </div>
    <hr>
    <div class="row table-responsive">
        <table class="table table-borderless table-hover">
            <thead class="thead-light">
              <th scope="col">Nome</th>
              <th scope="col">Curso</th>
              <th scope="col">E-mail</th>
              <th scope="col">SIAPE</th>
              <th scope="col"></th>
            </thead>
            <tbody>
              {% for doc in docentes %}
                <td>{{ doc.nome }}</td>
                <td>{{ doc.curso.nome }}</td>
                <td>{{ doc.email }}</td>
                
                <td>
                    {{ doc.siape }} 
                </td>
                <!-- buttons -->
                <td><a href="{% url 'docente_edit' pk=doc.pk %}">Editar</a></td>
              </tr>
              {% endfor %}        
            </tbody>
        </table>
    </div> 

    <div class="row add-table">
      <a href="{% url 'docente_new' %}" class="top-menu"><span class="glyphicon glyphicon-plus">Adicionar Docente</span></a>
    </div> 
{% endblock %}

sgt/app/templates/app/orientacoes_matricula_list.html
{% extends 'app/base2.html' %}

{% block content %}
    <div class="row">
        <div class="form-group col-md-12">
            <h2>Orientações de Matrícula</h2>
        </div>
    </div>
    <hr>
    <div class="row table-responsive">
        <table class="table table-borderless table-hover">
            <thead class="thead-light">
              <th scope="col">Discente</th>
              <th scope="col">Matrícula</th>
              <th scope="col"></th>
              <th scope="col"></th>
              <th scope="col"></th>              
            </thead>
            <tbody>
              {% for ori in orientacoes %}
              {% ifequal ori.status "S" %}
                <tr style="color:green;">
              {% else %}
                <tr>
              {% endifequal %}
                  <td>{{ ori.discente.nome }}</td>
                  <td>{{ ori.discente.matricula }}</td>
                  
                  <!-- buttons -->
                  <td><a href="{% url 'orientacao_matricula_export' pk=ori.pk %}">Exportar PDF</a></td>
                  <td><a href="{% url 'orientacao_matricula_edit' pk=ori.pk %}">Editar</a></td>     
                  <td><a href="{% url 'orientacao_matricula_remove' pk=ori.pk %}">Excluir</a></td>               
                </tr>
              {% endfor %}        
            </tbody>
        </table>
    </div> 

    <div class="row add-table">
      {% ifequal user.groups.all.0.name "Tutor" %}
        <a href="{% url 'orientacao_matricula_new' %}" class="top-menu"><span class="glyphicon glyphicon-plus">Adicionar Orientação de Matrícula</span></a>
      {% endifequal %}
    </div> 
{% endblock %}

{% block js %}
<script type="text/javascript">
  $(document).ready(function(){
    $('[data-toggle="tooltip"]').tooltip();
  });
</script>
{% endblock %}

sgt/app/templates/app/password_reset_confirm.html
{% extends 'app/base.html' %}

{% block content %}

  {% load crispy_forms_tags %}  
  
  <!--Password Reset Confirm-->
    <div class="container p-5">
	    <h2 class="font-weight-bold mt-3">Reiniciar Senha - Confirmação</h2>
		<hr>
        <p>Por favor insira a nova senha.</p>
        <form method="POST">
            {% csrf_token %}
            {{ form|crispy }}                    
            <button class="btn btn-primary" type="submit">Trocar Senha</button>
        </form>
    </div>

{% endblock %}